ARG SUSE_IMAGE=opensuse/leap:15
FROM $SUSE_IMAGE
RUN zypper -n install kernel-default \
                      kexec-tools    \
                      makedumpfile   \
                      which          \
                      openssh        \
                      tar            \
                      kmod-compat    \
                      xfsprogs       \
                      binutils
